import { login, register } from '../services/auth.js';
import { $, toast } from '../utils/helpers.js';
export function renderAuth(root){
 root.innerHTML=`<div class="auth-wrap"><section class="hero-card"><div><span class="badge">✦ Atlantis Workspace • Garuda Night Theme</span><h1 class="hero-title"><span class="gradient">Atlantis PMS</span><br/>Project Management System</h1><p class="muted" style="font-size:18px;max-width:760px">Dashboard super detail untuk mengatur project, task, deadline, team, budgeting, activity log, dan report realtime berbasis Firebase.</p><div class="hero-grid"><div class="mini"><b>Realtime</b><span class="muted">Database live sync</span></div><div class="mini"><b>Secure</b><span class="muted">Auth + database rules</span></div><div class="mini"><b>Complex</b><span class="muted">Project, task, finance</span></div></div></div><div class="logo"><div class="logo-mark">A</div><div><b>Atlantis PMS</b><div class="muted">Push-ready for GitHub Pages</div></div></div></section><section class="auth-card"><h2>Masuk Workspace</h2><p class="muted">Login dulu biar semua data project aman dan tersimpan per akun Firebase.</p><div class="tabs"><button class="tab active" id="loginTab">Login</button><button class="tab" id="regTab">Register</button></div><form class="form" id="authForm"><div class="field name-field hide"><label>Nama Lengkap</label><input class="input" id="name" placeholder="Hiro Atlantis" /></div><div class="field"><label>Email</label><input class="input" id="email" type="email" placeholder="admin@atlantis.local" required /></div><div class="field"><label>Password</label><input class="input" id="password" type="password" minlength="6" placeholder="Minimal 6 karakter" required /></div><button class="btn primary" id="submitBtn">Login</button><p class="muted">User baru otomatis role <b>member</b>. Untuk owner/admin, ubah role lewat Firebase Database.</p></form></section></div>`;
 let mode='login';
 $('#loginTab').onclick=()=>{mode='login';$('#loginTab').classList.add('active');$('#regTab').classList.remove('active');$('.name-field').classList.add('hide');$('#submitBtn').textContent='Login'};
 $('#regTab').onclick=()=>{mode='register';$('#regTab').classList.add('active');$('#loginTab').classList.remove('active');$('.name-field').classList.remove('hide');$('#submitBtn').textContent='Buat Akun'};
 $('#authForm').onsubmit=async e=>{e.preventDefault();try{ if(mode==='login') await login($('#email').value,$('#password').value); else await register($('#name').value||'Atlantis Member',$('#email').value,$('#password').value); toast('Berhasil masuk Atlantis PMS'); }catch(err){toast(err.message)}};
}
